### ISSUE TITLE
Not available in  Chrome Web Store.

### ISSUE THREAD

**Issue by DF-wu** [ychsieh95/AppleDaily-Viewer#2]
Not available in  Chrome Web Store.

Was it reported or removed?

**Comment by ychsieh95** [comment]
Both, but this extension is also effective now. So if you want to use this extension, you should:

1. Clone this repository.
2. Install it by `Load unpacked` from `More tools` > `Extensions` (remember that you have to enable `Developer mode` before).

I'll modify `README.md` later. Thanks for your giving.
